server:
  port: 8020
spring:
  application:
    name: menuService
  datasource:
    url: jdbc:mysql://localhost:3306/ordersystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver #用于mysql connector 为6.0以上,若使用com.mysql.jdbc.Driver  6.0以下就会报错
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ddfoever.entity