server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false #if register by itself
    fetch-registry: false #if synchronzied data from other eureka server